### ISSUE TITLE
Desktop app on Linux

### ISSUE THREAD

**Issue by maks** [leoafarias/sidekick#4]
Thanks for building the desktop app, its a very nice UI! I've also been using the cli for a little while now instead of manually managing symlinks and find it very helpful.

Doing a quick check I built and ran on Linux desktop (on master) without any issues. 

Would be nice to add Linux desktop builds for future releases here on GH and update the Readme to mention that it works on Linux too.

**Comment by aguilaair** [comment]
Hey! #11 adds a desktop app that will run on Linux, however there is still quite a lot that can be done to make the experience better, I had experimented with making .deb and .rmp packages for Linux, but found that they weren't as straightforward. I also tried building a snap, which works locally but for some reason fails on GitHub Actions because on a Windows dependency (no idea why), so this is still very much work in progress.
