### ISSUE TITLE
Unable to open application on macOS Big Sur

### ISSUE THREAD

**Issue by Lootwig** [leoafarias/sidekick#49]
This appears after copying the dmg to Applications & running:

![image](https://user-images.githubusercontent.com/39827040/115032331-7a282b00-9ec9-11eb-8138-1dc4a7069b2b.png)

**Comment by leoafarias** [comment]
I will update the documentation, but this is correct when downloading an app not signed by Apple. I will look into signing once we reach stable.

Preferences > Security > Open Anyways (You will see sidekick show up there if it was the last app you tried to open)

**Comment by tobiasht** [comment]
It is the same issue for pretty much any application you install outside of the App Store as long as they are no specifically signed. There are two very easy solutions though:

A: Hold down "ctrl" while opening the application. 

B: Go to _Settings_ -> _Security & Privacy_ -> _General_  and press "Open Anyway", where it states _"Sidekick.app was blocked from use because it is not from an identified developer."_

No need to open an issue for this.
